apiVersion: v1
kind: ConfigMap
metadata:
  name: flodrama-config
  namespace: flodrama
data:
  NODE_ENV: "production"
  REDIS_HOST: "flodrama-redis.flodrama.svc.cluster.local"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
  MEDIA_STORAGE_PATH: "/storage/media"
  RECOMMANDATION_CACHE_TTL: "300"
  RECOMMANDATION_MAX_ITEMS: "50"
  CORS_ORIGINS: "https://flodrama.com"
  RATE_LIMIT_WINDOW: "60000"
  RATE_LIMIT_MAX: "100"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flodrama-prometheus-config
  namespace: flodrama
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
