version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g yarn
      - npm install -g turbo
      
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - yarn install
      
  build:
    commands:
      - echo "Building the monorepo..."
      - if [ "$BUILD_TARGET" = "web" ]; then
          echo "Building web application...";
          yarn workspace web build;
        elif [ "$BUILD_TARGET" = "mobile" ]; then
          echo "Building mobile application...";
          yarn workspace mobile build;
        elif [ "$BUILD_TARGET" = "desktop" ]; then
          echo "Building desktop application...";
          yarn workspace desktop build;
        else
          echo "Building all applications...";
          yarn build;
        fi
        
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - if [ "$BUILD_TARGET" = "web" ]; then
          echo "Invalidating CloudFront cache...";
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*";
        fi

artifacts:
  files:
    - apps/web/dist/**/*
    - apps/mobile/build/**/*
    - apps/desktop/dist/**/*
  base-directory: '.'
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
    - '.yarn/cache/**/*'
