# Configuration globale pour le projet FloDrama

[env.production]
name = "flodrama"
type = "webpack"
account_id = "42fc982266a2c31b942593b18097e4b3"
workers_dev = true

# Variables d'environnement communes
[vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
