name = "flodrama-recommendations"
main = "src/index.js"
compatibility_date = "2023-05-18"
nodejs_compat = true

# Environnement de développement
[env.dev]
name = "flodrama-recommendations-dev"
vars = { ENVIRONMENT = "development" }

# Environnement de production
[env.prod]
name = "flodrama-recommendations-prod"
vars = { ENVIRONMENT = "production" }

# Planification des tâches
[triggers]
crons = ["0 0 * * *"] # Tous les jours à minuit

# Liaison avec la base de données D1
[[d1_databases]]
binding = "DB"
database_name = "flodrama-db"
database_id = "39a4a8fd-f1fd-49ab-abcc-290fd473a311"

# Liaison avec le namespace KV
[[kv_namespaces]]
binding = "FLODRAMA_METADATA"
id = "7388919bd83241cfab509b44f819bb2f"

# Configuration des variables d'environnement
[vars]
ENVIRONMENT = "production"
# API_KEY doit être défini via wrangler secret

# Configuration des secrets
# Pour définir les secrets, exécuter:
# npx wrangler secret put SUPABASE_SERVICE_KEY
# npx wrangler secret put API_KEY
