name = "flodrama-scraper"
main = "src/index.js"
compatibility_date = "2023-09-04"
account_id = "42fc982266a2c31b942593b18097e4b3"
workers_dev = true

# Configuration du format de module
compatibility_flags = ["nodejs_compat"]

# Planification (toutes les 24 heures à minuit)
[triggers]
crons = ["0 0 * * *"]

# Liaison avec D1
[[d1_databases]]
binding = "DB"
database_name = "flodrama-db"
database_id = "39a4a8fd-f1fd-49ab-abcc-290fd473a311"

# Liaison avec R2
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "flodrama-storage"

# Liaison avec KV
[[kv_namespaces]]
binding = "METADATA"
id = "7388919bd83241cfab509b44f819bb2f"

[vars]
ENVIRONMENT = "production"
CLOUDFLARE_STREAM_TOKEN = "mGa7n-h-E9RJi3q9IGfpwF1JjPQx57hhRxQuGC0a"
SCRAPINGBEE_API_KEY = "API_KEY_SCRAPINGBEE"
PARSEHUB_API_KEY = "tZAo7B3UOrM7"
