-- Script de migration des données mockées vers Cloudflare D1

-- Dramas
INSERT OR REPLACE INTO dramas (id, title, description, poster, backdrop, rating, year, episode_count, season_count, genres, language, country, status, created_at, updated_at)
VALUES 
('drama-1', 'Les mystères de l''Empire', 'Dans la Chine ancienne, une jeune femme devient enquêtrice pour résoudre des mystères qui menacent l''empire. Entre complots politiques et aventures romantiques, suivez son parcours extraordinaire.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/drama-1.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/drama-1.jpg', 4.9, 2023, 16, 1, '["Historique", "Mystère", "Romance"]', 'Mandarin', 'Chine', 'completed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('drama-2', 'Destins croisés', 'Trois familles que tout oppose voient leurs vies bouleversées par un événement tragique. Une exploration profonde des relations humaines et du pardon.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/drama-2.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/drama-2.jpg', 4.7, 2022, 20, 1, '["Drame", "Famille"]', 'Coréen', 'Corée du Sud', 'completed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('drama-3', 'Médecin de cœur', 'Un brillant chirurgien cardiaque doit faire face à son propre passé traumatique tout en sauvant des vies dans l''un des hôpitaux les plus prestigieux de Séoul. Un drame médical émouvant et captivant.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/drama-3.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/drama-3.jpg', 4.8, 2023, 16, 1, '["Médical", "Drame", "Romance"]', 'Coréen', 'Corée du Sud', 'ongoing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('drama-4', 'Le bureau des légendes', 'Dans un bureau gouvernemental secret, une équipe d''agents spéciaux enquête sur des phénomènes surnaturels liés aux légendes asiatiques. Un mélange unique de thriller, d''horreur et de mythologie.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/drama-4.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/drama-4.jpg', 4.6, 2022, 12, 2, '["Fantastique", "Thriller", "Mystère"]', 'Thaïlandais', 'Thaïlande', 'ongoing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('drama-5', 'Dynastie impériale', 'La saga épique d''une famille royale dans la Chine ancienne, leurs luttes pour le pouvoir, leurs amours interdites et leurs sacrifices. Une fresque historique somptueuse aux costumes magnifiques.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/drama-5.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/drama-5.jpg', 4.9, 2021, 50, 1, '["Historique", "Drame", "Romance"]', 'Mandarin', 'Chine', 'completed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Films
INSERT OR REPLACE INTO films (id, title, description, poster, backdrop, rating, year, duration, genres, language, country, created_at, updated_at)
VALUES 
('film-1', 'La légende du guerrier', 'Un guerrier légendaire doit faire face à son plus grand défi : protéger son village et retrouver sa famille disparue. Une épopée captivante mêlant arts martiaux et spiritualité.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/film-1.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/film-1.jpg', 4.8, 2023, 125, '["Action", "Aventure", "Drame"]', 'Mandarin', 'Chine', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('film-2', 'Sous les cerisiers en fleurs', 'Quand un jeune architecte retourne dans sa ville natale, il redécouvre son premier amour. Une histoire touchante de seconde chance dans un cadre magnifique du Japon rural.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/film-2.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/film-2.jpg', 4.6, 2022, 118, '["Romance", "Drame"]', 'Japonais', 'Japon', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('film-3', 'Le secret des montagnes', 'Dans un village isolé des montagnes coréennes, une jeune femme découvre un ancien secret qui pourrait changer le destin de sa communauté. Un thriller atmosphérique aux paysages à couper le souffle.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/film-3.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/film-3.jpg', 4.7, 2023, 132, '["Thriller", "Mystère", "Drame"]', 'Coréen', 'Corée du Sud', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('film-4', 'L''héritage du dragon', 'Après la mort de son grand-père, un jeune homme hérite d''un médaillon mystérieux qui le conduit dans une quête à travers l''Asie pour découvrir ses origines. Un film d''aventure épique avec des scènes d''action spectaculaires.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/film-4.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/film-4.jpg', 4.5, 2021, 145, '["Action", "Aventure", "Fantastique"]', 'Mandarin', 'Chine', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Animes
INSERT OR REPLACE INTO animes (id, title, description, poster, backdrop, rating, year, episode_count, season_count, genres, language, country, status, created_at, updated_at)
VALUES 
('anime-1', 'Le monde des esprits', 'Une jeune fille découvre un monde parallèle peuplé d''esprits et doit trouver un moyen de sauver ses parents transformés en créatures mystiques. Une aventure fantastique inoubliable.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/anime-1.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/anime-1.jpg', 4.9, 2021, 24, 1, '["Fantastique", "Aventure", "Surnaturel"]', 'Japonais', 'Japon', 'completed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('anime-2', 'Chasseurs de démons', 'Après la tragédie qui a frappé sa famille, un jeune homme décide de devenir chasseur de démons pour venger les siens et protéger l''humanité. Un récit épique de courage et de détermination.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/anime-2.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/anime-2.jpg', 4.8, 2022, 26, 2, '["Action", "Surnaturel", "Drame"]', 'Japonais', 'Japon', 'ongoing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('anime-3', 'Académie des héros', 'Dans un monde où 80% de la population possède des super-pouvoirs, un jeune garçon sans don rêve de devenir un héros. Son destin bascule lorsqu''il rencontre le plus grand héros de tous les temps.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/anime-3.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/anime-3.jpg', 4.7, 2023, 25, 6, '["Action", "Super-héros", "École"]', 'Japonais', 'Japon', 'ongoing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('anime-4', 'Titans en guerre', 'L''humanité vit retranchée derrière d''immenses murs pour se protéger de créatures gigantesques qui dévorent les humains. Un jeune homme dont la mère a été tuée par ces monstres jure de les exterminer tous.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/anime-4.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/anime-4.jpg', 4.9, 2020, 75, 4, '["Action", "Drame", "Horreur", "Fantastique"]', 'Japonais', 'Japon', 'completed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Bollywood
INSERT OR REPLACE INTO bollywood (id, title, description, poster, backdrop, rating, year, duration, genres, language, country, created_at, updated_at)
VALUES 
('bollywood-1', 'Amour éternel', 'Une histoire d''amour qui transcende les classes sociales et les traditions dans l''Inde moderne. Entre danses colorées et émotions intenses, suivez ce couple qui défie tous les obstacles.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/bollywood-1.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/bollywood-1.jpg', 4.7, 2023, 165, '["Romance", "Musical", "Drame"]', 'Hindi', 'Inde', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('bollywood-2', 'Le destin d''un héros', 'Un homme ordinaire se retrouve dans des circonstances extraordinaires et doit devenir le héros que son pays attend. Un spectacle grandiose mêlant action, drame et moments musicaux.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/bollywood-2.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/bollywood-2.jpg', 4.6, 2022, 180, '["Action", "Patriotique", "Drame"]', 'Hindi', 'Inde', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('bollywood-3', 'Danse avec les étoiles', 'Une jeune danseuse talentueuse des quartiers populaires de Mumbai rêve de devenir une star de Bollywood. Son parcours semé d''embûches la conduira à découvrir le vrai sens de la passion et du sacrifice.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/bollywood-3.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/bollywood-3.jpg', 4.8, 2023, 155, '["Musical", "Drame", "Romance"]', 'Hindi', 'Inde', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('bollywood-4', 'Le roi des voleurs', 'Inspiré d''une histoire vraie, ce film raconte l''ascension et la chute du plus célèbre voleur de bijoux de l''Inde, qui dérobait aux riches pour aider les pauvres. Un thriller palpitant aux rebondissements inattendus.', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/bollywood-4.jpg', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/bollywood-4.jpg', 4.5, 2021, 175, '["Thriller", "Biopic", "Crime"]', 'Hindi', 'Inde', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Création d'un utilisateur de test
INSERT OR REPLACE INTO users (id, email, name, avatar, preferences, created_at, updated_at)
VALUES 
('user-1', 'test@flodrama.com', 'Utilisateur Test', 'https://fffgoqubrbgppcqqkyod.supabase.co/storage/v1/object/public/flodrama-content/placeholders/avatar-1.jpg', '{"theme": "dark", "language": "fr", "notifications": true}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Création de quelques favoris pour l'utilisateur de test
INSERT OR REPLACE INTO favorites (id, user_id, content_id, content_type, created_at)
VALUES 
('fav-1', 'user-1', 'drama-1', 'drama', CURRENT_TIMESTAMP),
('fav-2', 'user-1', 'film-2', 'film', CURRENT_TIMESTAMP),
('fav-3', 'user-1', 'anime-3', 'anime', CURRENT_TIMESTAMP);

-- Création de quelques vues pour l'utilisateur de test
INSERT OR REPLACE INTO views (id, user_id, content_id, content_type, progress, created_at, updated_at)
VALUES 
('view-1', 'user-1', 'drama-1', 'drama', 75, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('view-2', 'user-1', 'film-2', 'film', 45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('view-3', 'user-1', 'anime-3', 'anime', 90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Création de quelques recommandations pour l'utilisateur de test
INSERT OR REPLACE INTO recommendations (id, user_id, content_id, content_type, score, reason, created_at)
VALUES 
('rec-1', 'user-1', 'drama-3', 'drama', 0.95, 'Basé sur votre intérêt pour les dramas médicaux', CURRENT_TIMESTAMP),
('rec-2', 'user-1', 'film-1', 'film', 0.85, 'Basé sur votre intérêt pour les films d''action', CURRENT_TIMESTAMP),
('rec-3', 'user-1', 'anime-2', 'anime', 0.90, 'Basé sur votre intérêt pour les animes d''action', CURRENT_TIMESTAMP);
