name = "flodrama-api"
main = "src/index-minimal.js"
compatibility_date = "2023-11-15"

# Variables d'environnement pour les différents environnements
[vars]
ENVIRONMENT = "development"
STREAM_ACCOUNT_ID = "ehlynuge6dnzfnfd"
LOG_LEVEL = "debug"

# Configuration simplifiée pour premier déploiement
# Les KV et R2 seront ajoutés après le premier déploiement réussi
