name: Deploy CORS Proxy

on:
  push:
    branches: [ main ]
    paths:
      - 'cors-proxy/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd cors-proxy
          npm install

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: cors-proxy
          branch: gh-pages
          target-folder: proxy
