name: Pipeline de Scraping FloDrama

on:
  # Exécution manuelle avec options configurables
  workflow_dispatch:
    inputs:
      skip_scraping:
        description: 'Sauter l''étape de scraping'
        required: false
        default: false
        type: boolean
      skip_enrichment:
        description: 'Sauter l''étape d''enrichissement'
        required: false
        default: false
        type: boolean
      skip_distribution:
        description: 'Sauter l''étape de distribution'
        required: false
        default: false
        type: boolean
      debug_mode:
        description: 'Activer le mode debug'
        required: false
        default: false
        type: boolean
      use_relay_service:
        description: 'Utiliser le service relais Render pour le scraping'
        required: false
        default: true
        type: boolean
      sources:
        description: 'Sources à scraper (séparées par des virgules, vide = toutes)'
        required: false
        type: string
      recent_only:
        description: 'Ne scraper que les contenus récents (année courante - 2 ans)'
        required: false
        default: true
        type: boolean
  
  # Exécution planifiée (tous les jours à 2h du matin)
  schedule:
    - cron: '0 2 * * *'
  
  # Exécution lors d'un push sur les branches main et integration-cloudflare
  push:
    branches:
      - main
      - integration-cloudflare
    paths:
      - '.github/scripts/stealth/**'
      - '.github/workflows/scraping-pipeline-optimise.yml'
      - 'cloudflare/scraping/**'

# Définition des limites de temps et des permissions
concurrency:
  group: scraping-${{ github.ref }}
  cancel-in-progress: false

jobs:
  scraping-pipeline:
    name: Exécution du pipeline de scraping
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY || 'rnd_DJfpQC9gEu4KgTRvX8iQzMXxrteP' }}
      USE_RELAY_SERVICE: ${{ github.event.inputs.use_relay_service != 'false' }}
      DEBUG_MODE: ${{ github.event.inputs.debug_mode == 'true' }}
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
      
      - name: Configuration de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Installation des dépendances
        run: |
          # Désactiver les scripts d'installation automatiques
          npm install --ignore-scripts
          npm install -g wrangler
          # Installation directe des dépendances nécessaires
          npm install --no-save fs-extra axios cheerio playwright playwright-extra playwright-extra-plugin-stealth
      
      - name: Installation des dépendances de Playwright
        run: |
          npx playwright install-deps
          npx playwright install chromium
      
      # Vérification du service relais Render
      - name: Vérification du service relais Render
        if: ${{ github.event.inputs.skip_scraping != 'true' && github.event.inputs.use_relay_service != 'false' }}
        id: check_relay
        run: |
          echo "🔄 Vérification de la disponibilité du service relais Render..."
          RELAY_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $RENDER_API_KEY" https://flodrama-scraper.onrender.com/status)
          
          if [ "$RELAY_STATUS" = "200" ]; then
            echo "✅ Service relais Render disponible"
            echo "use_relay_service=true" >> $GITHUB_ENV
          else
            echo "⚠️ Service relais Render indisponible (code: $RELAY_STATUS), utilisation du fallback local"
            echo "use_relay_service=false" >> $GITHUB_ENV
          fi
      
      # Étape de scraping
      - name: Exécution du scraping
        if: ${{ github.event.inputs.skip_scraping != 'true' }}
        id: scraping
        run: |
          echo "🔍 Démarrage du scraping..."
          
          # Déterminer les sources à scraper
          SOURCES_ARG=""
          if [ -n "${{ github.event.inputs.sources }}" ]; then
            SOURCES_ARG="--sources=${{ github.event.inputs.sources }}"
            echo "Sources spécifiées: ${{ github.event.inputs.sources }}"
          else
            echo "Scraping de toutes les sources"
          fi
          
          # Déterminer si on ne scrape que les contenus récents
          RECENT_ONLY="${{ github.event.inputs.recent_only != 'false' }}"
          if [ "$RECENT_ONLY" = "true" ]; then
            # Calculer la plage d'années dynamique (année courante - 2 ans)
            CURRENT_YEAR=$(date +"%Y")
            MIN_YEAR=$((CURRENT_YEAR - 2))
            echo "Filtrage activé: uniquement les contenus entre $MIN_YEAR et $CURRENT_YEAR"
            YEARS_ARG="--years=$MIN_YEAR,$CURRENT_YEAR"
          else
            echo "Aucun filtrage par année: tous les contenus seront scrapés"
            YEARS_ARG=""
          fi
          
          # Exécuter le script de scraping optimisé
          node .github/scripts/stealth/scraper-optimise.js $SOURCES_ARG $YEARS_ARG
          
          # Si nous utilisons Cloudflare Workers pour le scraping, lancer également la version Cloudflare
          if [ "$RECENT_ONLY" = "true" ]; then
            echo "🔍 Lancement du scraping via Cloudflare Workers..."
            # Mettre à jour les services Cloudflare avec la plage d'années dynamique
            cd cloudflare/recommendations
            
            # Mettre à jour le service de recommandation pour qu'il utilise la plage d'années dynamique
            sed -i "s/WHERE release_year BETWEEN [0-9]\{4\} AND [0-9]\{4\}/WHERE release_year BETWEEN $MIN_YEAR AND $CURRENT_YEAR/g" src/services/recommendation-service.js
            
            # Déployer les modifications
            ./deploy.sh
            
            # Lancer le scraping pour chaque source via l'API Cloudflare
            API_KEY=$(grep -o 'API Key: [a-f0-9]\{32\}' deploy.log | cut -d' ' -f3)
            
            if [ -n "$API_KEY" ]; then
              echo "Lancement du scraping via l'API Cloudflare avec la clé: $API_KEY"
              
              # Liste des sources à scraper
              if [ -n "${{ github.event.inputs.sources }}" ]; then
                IFS=',' read -ra SOURCES <<< "${{ github.event.inputs.sources }}"
              else
                SOURCES=("kissasian" "dramacool" "viewasian" "voirdrama" "gogoanime" "nekosama" "voiranime" "vostfree" "streamingdivx" "filmcomplet" "bollyplay" "hindilinks4u")
              fi
              
              for SOURCE in "${SOURCES[@]}"; do
                echo "Scraping de la source: $SOURCE"
                curl -X POST https://flodrama-recommendations-prod.florifavi.workers.dev/api/scrape \
                  -H "X-API-Key: $API_KEY" \
                  -H "Content-Type: application/json" \
                  -d '{"source_id": "'$SOURCE'", "target_years": ['$MIN_YEAR', '$CURRENT_YEAR']}'
                
                # Attendre 5 secondes entre chaque source
                sleep 5
              done
            else
              echo "Impossible de récupérer la clé API, le scraping via Cloudflare n'a pas été lancé"
            fi
            
            cd ../..
          fi
          
          # Vérifier si des données ont été générées
          if [ -d "./cloudflare/scraping/output" ] && [ "$(find ./cloudflare/scraping/output -name '*.json' | wc -l)" -gt 0 ]; then
            echo "✅ Scraping terminé avec succès"
            echo "scraping_success=true" >> $GITHUB_ENV
          else
            echo "⚠️ Le scraping n'a pas généré de données, vérifiez les logs pour plus d'informations"
            echo "scraping_success=false" >> $GITHUB_ENV
          fi
      
      # Vérification du statut de scraping
      - name: Vérification du statut de scraping
        id: check_scraping
        if: ${{ github.event.inputs.skip_scraping != 'true' }}
        run: |
          if [ -d "./cloudflare/scraping/output" ] && [ "$(find ./cloudflare/scraping/output -name '*.json' | wc -l)" -gt 0 ]; then
            echo "::set-output name=success::true"
          else
            echo "::set-output name=success::false"
          fi
      
      # Étape d'enrichissement des données
      - name: Enrichissement des données via TMDB
        if: ${{ github.event.inputs.skip_enrichment != 'true' && (steps.scraping.outcome == 'success' || steps.check_scraping.outputs.success == 'true') }}
        run: |
          echo "🔍 Démarrage de l'enrichissement des données..."
          node .github/scripts/enrichment/tmdb-enricher.js
          echo "✅ Enrichissement terminé avec succès"
      
      # Étape de distribution des données
      - name: Distribution des données vers Cloudflare D1
        if: ${{ github.event.inputs.skip_distribution != 'true' && (steps.scraping.outcome == 'success' || steps.check_scraping.outputs.success == 'true' || github.event.inputs.skip_scraping == 'true') }}
        run: |
          echo "📦 Démarrage de la distribution des données..."
          
          # Créer la base de données D1 si elle n'existe pas
          wrangler d1 create flodrama-content --json || echo "Base de données existe déjà"
          
          # Exécuter les migrations de schéma
          cd cloudflare/scraping
          wrangler d1 execute flodrama-content --file=./schema.sql
          
          # Déterminer si on ne distribue que les contenus récents
          RECENT_ONLY="${{ github.event.inputs.recent_only != 'false' }}"
          if [ "$RECENT_ONLY" = "true" ]; then
            # Calculer la plage d'années dynamique (année courante - 2 ans)
            CURRENT_YEAR=$(date +"%Y")
            MIN_YEAR=$((CURRENT_YEAR - 2))
            echo "Filtrage activé: uniquement les contenus entre $MIN_YEAR et $CURRENT_YEAR"
            
            # Supprimer les contenus anciens de la base de données
            echo "Suppression des contenus antérieurs à $MIN_YEAR..."
            wrangler d1 execute flodrama-content --command="DELETE FROM contents WHERE release_year < $MIN_YEAR"
            
            # Importer les données avec le filtre d'année
            echo "Importation des données récentes uniquement..."
            node ./import-to-d1.js --min-year=$MIN_YEAR
          else
            # Importer toutes les données sans filtre
            echo "Importation de toutes les données sans filtre d'année..."
            node ./import-to-d1.js
          fi
          
          # Synchroniser avec la base de données de recommandation
          echo "Synchronisation avec la base de données de recommandation..."
          cd ../recommendations
          
          # Déployer les modifications si nécessaire
          if [ "$RECENT_ONLY" = "true" ]; then
            # Mettre à jour le service de recommandation pour qu'il utilise la plage d'années dynamique
            CURRENT_YEAR=$(date +"%Y")
            MIN_YEAR=$((CURRENT_YEAR - 2))
            
            # Vérifier si le service a déjà été mis à jour dans l'étape de scraping
            if ! grep -q "WHERE release_year BETWEEN $MIN_YEAR AND $CURRENT_YEAR" src/services/recommendation-service.js; then
              sed -i "s/WHERE release_year BETWEEN [0-9]\{4\} AND [0-9]\{4\}/WHERE release_year BETWEEN $MIN_YEAR AND $CURRENT_YEAR/g" src/services/recommendation-service.js
              ./deploy.sh
            fi
          fi
          
          cd ../..
          
          echo "✅ Distribution terminée avec succès"
      
      # Notification de résultat
      - name: Notification Discord
        if: always()
        run: |
          STATUS="${{ job.status }}"
          COLOR="0xFF0000"  # Rouge par défaut (échec)
          
          if [ "$STATUS" == "success" ]; then
            COLOR="0x00FF00"  # Vert (succès)
            MESSAGE="✅ Le pipeline de scraping s'est terminé avec succès!"
          else
            MESSAGE="❌ Le pipeline de scraping a échoué!"
          fi
          
          # Ajouter des informations sur le mode de scraping utilisé
          if [ "$USE_RELAY_SERVICE" == "true" ]; then
            SCRAPING_MODE="Service relais Render"
          else
            SCRAPING_MODE="Scraping local + fallback TMDB"
          fi
          
          # Envoyer la notification Discord avec plus de détails
          curl -H "Content-Type: application/json" \
               -d "{\"embeds\": [{\"title\": \"FloDrama Scraping\", \"description\": \"$MESSAGE\", \"color\": $COLOR, \"fields\": [{\"name\": \"Mode de scraping\", \"value\": \"$SCRAPING_MODE\", \"inline\": true}, {\"name\": \"Déclenché par\", \"value\": \"${{ github.event_name }}\", \"inline\": true}, {\"name\": \"Date\", \"value\": \"$(date +\"%d/%m/%Y %H:%M\")\", \"inline\": true}]}]}" \
               $DISCORD_WEBHOOK
