name: Scrapy Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Exécution quotidienne à minuit
  workflow_dispatch:  # Permet l'exécution manuelle

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scrapy requests scrapy-user-agents
      
      - name: Run VoirDrama spider
        run: |
          cd scrapy_project/flodrama_scraper
          scrapy crawl voirdrama -s CLOSESPIDER_ITEMCOUNT=250
        env:
          CLOUDFLARE_WORKER_URL: ${{ secrets.CLOUDFLARE_WORKER_URL }}
      
      - name: Run MyDramaList spider
        run: |
          cd scrapy_project/flodrama_scraper
          scrapy crawl mydramalist -s CLOSESPIDER_ITEMCOUNT=250
        env:
          CLOUDFLARE_WORKER_URL: ${{ secrets.CLOUDFLARE_WORKER_URL }}
      
      - name: Run VoirAnime spider
        run: |
          cd scrapy_project/flodrama_scraper
          scrapy crawl voiranime -s CLOSESPIDER_ITEMCOUNT=250
        env:
          CLOUDFLARE_WORKER_URL: ${{ secrets.CLOUDFLARE_WORKER_URL }}
      
      - name: Run DramaVostfr spider
        run: |
          cd scrapy_project/flodrama_scraper
          scrapy crawl dramavostfr -s CLOSESPIDER_ITEMCOUNT=250
        env:
          CLOUDFLARE_WORKER_URL: ${{ secrets.CLOUDFLARE_WORKER_URL }}
      
      - name: Run AnimeSama spider
        run: |
          cd scrapy_project/flodrama_scraper
          scrapy crawl animesama -s CLOSESPIDER_ITEMCOUNT=250
        env:
          CLOUDFLARE_WORKER_URL: ${{ secrets.CLOUDFLARE_WORKER_URL }}
