name: FloDrama Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Exécution quotidienne à minuit
  workflow_dispatch:  # Permet l'exécution manuelle

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          cd cloudflare/scraping
          npm install
      
      - name: Run VoirDrama spider
        run: |
          cd cloudflare/scraping
          npx wrangler dev src/index.js --local --env=dev --var SOURCE:voirdrama
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      
      - name: Run MyDramaList spider
        run: |
          cd cloudflare/scraping
          npx wrangler dev src/index.js --local --env=dev --var SOURCE:mydramalist
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      
      - name: Run VoirAnime spider
        run: |
          cd cloudflare/scraping
          npx wrangler dev src/index.js --local --env=dev --var SOURCE:voiranime
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      
      - name: Run DramaVostfr spider
        run: |
          cd cloudflare/scraping
          npx wrangler dev src/index.js --local --env=dev --var SOURCE:dramavostfr
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      
      - name: Run AnimeSama spider
        run: |
          cd cloudflare/scraping
          npx wrangler dev src/index.js --local --env=dev --var SOURCE:animesama
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
